BEGIN {FS="\",\""; printf("TITLE\tTEXT_KEY\tCATALOG_NUMBER\tOPUS\tTITLE_TRANSLATED\tARTIST_NAME\tTIME_PLAY_START\tTIME_PLAY_END\tLENGTH_SECONDS\tCOMPOSER\tARRANGER\tCONDUCTOR\tENSEMBLE\tSOLOIST_1\tSOLOIST_2\tSOLOIST_3\tSOLOIST_4\tSOLOIST_5\tSOLOIST_6\tALBUM_NAME\tRECORD_LABEL\tSPINE_NUMBER\tUPC\tRELEASE_YEAR\tNOTES\tISRC\tISWC\tMARKETING_LABEL\tCOPYRIGHT\n")
}
{ if (NR!=1) print substr($1,2) "\t\t\t\t\t\t" $5 "\t\t\t" $8 "\t\t" $10 "\t" $12 "\t" $11 "\t" $11 "\t" $11 "\t" $11 "\t" $11 "\t" $11 "\t\t" $6 "\t" $9 "\t\t\t\t\t\t\t\t"}
END { }
